version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

dockers:
  - image_templates:
      - "ghcr.io/bambootuna/tmuxui:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile.release
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=https://github.com/BambooTuna/tmuxui"
      - "--label=org.opencontainers.image.licenses=MIT"
  - image_templates:
      - "ghcr.io/bambootuna/tmuxui:{{ .Version }}-arm64"
    use: buildx
    dockerfile: Dockerfile.release
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=https://github.com/BambooTuna/tmuxui"
      - "--label=org.opencontainers.image.licenses=MIT"

docker_manifests:
  - name_template: "ghcr.io/bambootuna/tmuxui:{{ .Version }}"
    image_templates:
      - "ghcr.io/bambootuna/tmuxui:{{ .Version }}-amd64"
      - "ghcr.io/bambootuna/tmuxui:{{ .Version }}-arm64"
  - name_template: "ghcr.io/bambootuna/tmuxui:latest"
    image_templates:
      - "ghcr.io/bambootuna/tmuxui:{{ .Version }}-amd64"
      - "ghcr.io/bambootuna/tmuxui:{{ .Version }}-arm64"
